targets:
  $default:
    sources:
      include:
        - "pubspec.yaml"
        - $package$
        - integration_test/** # By default, build runner will not generate code in the integration folder
        - test/** # so we override paths for code generation here
        - lib/**
        - assets/**

    builders:
      json_serializable:
        options:
          field_rename: pascal
      flutter_gen_runner:
        options:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: step # this trick is required to share steps between widget and integration tests
          # testMethodName: customTestMethodName
          include: package:bdd_widget_test/bdd_options.yaml # you may add defaul external steps with this line
          externalSteps: # or list only steps that you need
            - package:bdd_widget_test/step/i_see_text.dart
            # - package:bdd_widget_test/step/i_dont_see_text.dart
            # - package:bdd_widget_test/step/i_see_multiple_texts.dart
            # - package:bdd_widget_test/step/i_tap_text.dart
            # - package:bdd_widget_test/step/i_see_icon.dart
            # - package:bdd_widget_test/step/i_dont_see_icon.dart
            # - package:bdd_widget_test/step/i_tap_icon.dart
            # - package:bdd_widget_test/step/i_see_rich_text.dart
            # - package:bdd_widget_test/step/i_dont_see_rich_text.dart
            # - package:bdd_widget_test/step/i_see_widget.dart
            # - package:bdd_widget_test/step/i_dont_see_widget.dart
            # - package:bdd_widget_test/step/i_see_exactly_widgets.dart
            # - package:bdd_widget_test/step/i_see_multiple_widgets.dart
            # - package:bdd_widget_test/step/i_enter_into_input_field.dart
            # - package:bdd_widget_test/step/i_see_disabled_elevated_button.dart
            # - package:bdd_widget_test/step/i_see_enabled_elevated_button.dart
            - package:bdd_widget_test/step/i_wait.dart
            # - package:bdd_widget_test/step/i_dismiss_the_page.dart
        generate_for:
          - test/**
          - integration_test/**
